name: CI Build for Azure Function App

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: 'MultiRegion.Functions'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './src/MultiRegion/MultiRegion.Functions'
  OUTPUT_PATH: './output'
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # - name: 'Resolve Project Dependencies Using Dotnet'
    #   shell: bash
    #   run: |
    #     pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
    #     dotnet build --configuration Release --output ./output
    #     popd

    - name: Publish functions
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet publish --configuration Release --output ./output
        popd

    - name: Zip Function App
      shell: pwsh
      run: Compress-Archive -Path "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output/*" -DestinationPath "${{ env.OUTPUT_PATH }}/MultiRegionFunctions.zip"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ${{ env.OUTPUT_PATH }}/MultiRegionFunctions.zip